export const NOTE_CARD_VIEW_STATUS = {
    THUMBNAIL: 'THUMBNAIL',
    DETAIL: 'DETAIL',
    EDITOR: 'EDIT',
}

export const SIGNIN_PAGE_VIEW_STATUS = {
    SIGNIN: 'SIGNIN',
    SIGNUP: 'SIGNUP',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
}

export const FORGOT_PASSWORD_PANEL_STATUS = {
    SEND_CONFIRM: 'SEND_CONFIRM',
    NEW_PASSWORD: 'NEW_PASSWORD',
}

export const BUTTON_STYLE = {
    NORMAL: 'NORMAL',
    SUBMIT: 'SUBMIT',
    DANGER: 'DANGER',
}

export const LOADING_STATUS = {
    LOADING: 'LOADING',
    IDLE: 'IDLE',
}

export const SORTING_CRITERIA = {
    CREATED_AT: 'CREATED_AT',
    UPDATED_AT: 'UPDATED_AT',
    HEADER: 'HEADER',
}
