export const VIEW_STATUS = {
    THUMBNAIL: 'THUMBNAIL',
    DETAIL: 'DETAIL',
    EDIT: 'EDIT',
}

export const LOGIN_PANEL_STATUS = {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    CONFIRM: 'CONFIRM',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
}

export const FORGOT_PASSWORD_PANEL_STATUS = {
    SEND_CONFIRM: 'SEND_CONFIRM',
    NEW_PASSWORD: 'NEW_PASSWORD',
}

export const BUTTON_STYLE = {
    NORMAL: 'NORMAL',
    SUBMIT: 'SUBMIT',
    DANGER: 'DANGER',
}

export const LOADING_STATUS = {
    LOADING: 'LOADING',
    IDLE: 'IDLE',
}
